# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: gAxn Application workflow

on: [push]
  # schedule:
  #   - cron: "0 0 1 * *"

jobs:
  Runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build container
        run: docker build -t gaxn -f cron/Dockerfile .
      - name: "Register valid domain on dev"
        run: docker run --rm  gaxn pipenv run python3 weather.py $GITHUB_WORKSPACE

    # steps:
    # - name: Checkout master branch
    #   uses: actions/checkout@master

    # - name: Set up Python 3.7
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.7

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install requests click flask pytest

    # - name: Run script
    #   run: |
    #     python cron/weather.py $GITHUB_WORKSPACE
